version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    container_name: 'request'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net
  db:
    container_name: 'postgresdb'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "5432:5432"

networks:
  rabbitmq_go_net:
    driver: bridge
